#spring:
#  application:
#    name: gateway-service
#
#  cloud:
#    gateway:
#      routes:
#        - id: storage-service
#          uri: lb://storage-service
#          predicates:
#            - Path=/storage/**
#          filters:
#            - StripPrefix=1
#
#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/notification/**
#          filters:
#            - StripPrefix=1
#
#        - id: elasticsearch-service
#          uri: lb://elasticsearch-service
#          predicates:
#            - Path=/elasticsearch/**
#          filters:
#            - StripPrefix=1
#
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/product/**
#          filters:
#            - StripPrefix=1
#
#        - id: profile-service
#          uri: lb://profile-service
#          predicates:
#            - Path=/profile/**
#          filters:
#            - StripPrefix=1
#
#        - id: banner-service
#          uri: lb://banner-service
#          predicates:
#            - Path=/banner/**
#          filters:
#            - StripPrefix=1
#
#        - id: cart-service
#          uri: lb://cart-service
#          predicates:
#            - Path=/cart/**
#          filters:
#            - StripPrefix=1
#
#        - id: location-service
#          uri: lb://location-service
#          predicates:
#            - Path=/location/**
#          filters:
#            - StripPrefix=1
#
#        - id: shopinfo-service
#          uri: lb://shopinfo-service
#          predicates:
#            - Path=/shopinfo/**
#          filters:
#            - StripPrefix=1
#
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1
#
#        - id: payment-service
#          uri: lb://payment-service
#          predicates:
#            - Path=/payment/**
#          filters:
#            - StripPrefix=1
#
#        - id: dashboard-service
#          uri: lb://dashboard-service
#          predicates:
#            - Path=/dashboard/**
#          filters:
#            - StripPrefix=1
#
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${JWK_URI:http://localhost:8180/realms/IamService}
#
#server:
#  port: ${SERVER_PORT:8686}
#
#springdoc:
#  swagger-ui:
#    enabled: true
#    urls:
#      - url: http://${STORAGE_HOST:localhost}:8080/swagger-doc/v3/api-docs/storage
#        name: Storage API
#
#management:
#  endpoints:
#    web:
#      expsure:
#        include: "*"
#
#  endpoint:
#    gateway:
#      enabled: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}